apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-you-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-you
  template:
    metadata:
      labels:
        app: hello-you
    spec:
      containers:
        - name: hello-you
          image: 573329840855.dkr.ecr.eu-west-3.amazonaws.com/ocd-cloud-lyon:$BUILD_NUMBER
          ports:
            - containerPort: 80
