apiVersion: apps/v1
kind: Deployment
metadata:
  name: $DeployName
  namespace : $NameSpace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
        - name: hello-you
          image: 573329840855.dkr.ecr.eu-west-3.amazonaws.com/$DockImageName:$env.BUILD_NUMBER
          ports:
            - containerPort: 80
