apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-you-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-you
  template:
    metadata:
      labels:
        app: hello-you
    spec:
      containers:
        - name: hello-you
          image: 573329840855.dkr.ecr.eu-west-3.amazonaws.com/ocd-cloud-lyon:$BUILD_NUMBER
          ports:
            - containerPort: 8000
apiVersion: v1
kind: Service
metadata:
  name: hello-you-svc
  #annotations:
    #service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  selector:
    app: hello-you
  ports:
    - protocol: TCP
      port: 8000
  type: LoadBalancer
