# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: 571253107823.dkr.ecr.eu-west-3.amazonaws.com/sma-maquette

nameOverride: ""
fullnameOverride: ""


service:
  type: NodePort
  port: 8000

