  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app:
    spec:
      containers:
        - name: 
          image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
          ports:
            - containerPort: 8000
      imagePullSecrets:
         - name: eu-west-3-ecr-registry